# Generated by Django 3.2.7 on 2021-09-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('expiration_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('work_hours_per_week', models.IntegerField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('job_fields', models.ManyToManyField(to='job.JobField')),
            ],
        ),
    ]
