# Generated by Django 3.2.7 on 2021-09-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='job_fields',
            field=models.ManyToManyField(blank=True, to='job.JobField'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
